import type { Idea, Category } from "./types"

export const mockCategories: Category[] = [
  { id: "1", name: "SaaS", color: "#3B82F6", created_at: new Date().toISOString() },
  { id: "2", name: "E-commerce", color: "#10B981", created_at: new Date().toISOString() },
  { id: "3", name: "Productivity", color: "#8B5CF6", created_at: new Date().toISOString() },
  { id: "4", name: "Health & Fitness", color: "#EF4444", created_at: new Date().toISOString() },
  { id: "5", name: "Education", color: "#F59E0B", created_at: new Date().toISOString() },
  { id: "6", name: "Finance", color: "#06B6D4", created_at: new Date().toISOString() },
  { id: "7", name: "Marketing", color: "#EC4899", created_at: new Date().toISOString() },
  { id: "8", name: "Developer Tools", color: "#6366F1", created_at: new Date().toISOString() },
]

export const mockIdeas: Idea[] = [
  {
    id: "1",
    problem: "Freelancers struggle to track billable hours across multiple clients",
    description: "As a freelance developer, I waste 30 minutes daily manually logging time across projects. Need something that auto-detects what I'm working on and bills accordingly.",
    reddit_url: "https://reddit.com/r/freelance",
    reddit_post_id: "abc123",
    category_id: "1",
    category: mockCategories[0],
    pain_score: 8,
    validation_score: 847,
    upvotes: 12,
    reddit_upvotes: 156,
    reddit_comments: 43,
    market_size: "Medium",
    competition_level: "Medium",
    analyzed: true,
    ai_analysis: {
      problem: "Freelancers struggle to track billable hours across multiple clients",
      painLevel: 8,
      targetCustomer: "Freelance developers, designers, and consultants managing 3+ clients simultaneously",
      marketSize: "Medium",
      competitionLevel: "Medium",
      monetizationIdeas: [
        "SaaS subscription at $15-30/month per user",
        "Team plans at $100-200/month for agencies",
        "Premium features: invoicing integration, advanced analytics"
      ],
      techStack: ["Next.js", "Electron", "Supabase", "Stripe"],
      buildTimeEstimate: "6-8 weeks for MVP with auto-tracking",
      keyInsights: [
        "42% of freelancers lose revenue due to poor time tracking",
        "Existing tools are either too complex or lack automation",
        "Opportunity to integrate with popular project management tools"
      ]
    },
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    problem: "Small businesses can't afford expensive email marketing tools",
    description: "Mailchimp is $300/mo for my 5,000 subscribers. I just need basic newsletters and automation without the crazy pricing.",
    reddit_url: "https://reddit.com/r/smallbusiness",
    reddit_post_id: "def456",
    category_id: "7",
    category: mockCategories[6],
    pain_score: 9,
    validation_score: 1243,
    upvotes: 23,
    reddit_upvotes: 287,
    reddit_comments: 89,
    market_size: "Large",
    competition_level: "High",
    analyzed: true,
    ai_analysis: {
      problem: "Small businesses can't afford expensive email marketing tools",
      painLevel: 9,
      targetCustomer: "Small businesses, solopreneurs, content creators with 1K-10K email subscribers",
      marketSize: "Large",
      competitionLevel: "High",
      monetizationIdeas: [
        "Volume-based pricing: $20/mo for 5K subscribers",
        "Pay-as-you-go model for occasional senders",
        "White-label option for agencies"
      ],
      techStack: ["Next.js", "PostgreSQL", "AWS SES", "Redis"],
      buildTimeEstimate: "10-12 weeks for MVP with basic automation",
      keyInsights: [
        "Email marketing is a $10B+ market growing at 13% annually",
        "Major pain point is pricing - opportunity for value pricing",
        "Integration with Shopify/WooCommerce is table stakes"
      ]
    },
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    problem: "Parents need help managing kids' screen time effectively",
    description: "My kids spend 6+ hours on devices daily. Built-in parental controls are too restrictive or too easy to bypass. Need smart limits that actually work.",
    reddit_url: "https://reddit.com/r/Parenting",
    reddit_post_id: "ghi789",
    category_id: "4",
    category: mockCategories[3],
    pain_score: 7,
    validation_score: 623,
    upvotes: 8,
    reddit_upvotes: 134,
    reddit_comments: 67,
    market_size: "Large",
    competition_level: "Medium",
    analyzed: false,
    ai_analysis: null,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    problem: "Developers waste hours setting up dev environments for new projects",
    description: "Every new project = 3-4 hours configuring linters, formatters, git hooks, CI/CD. Should be one-click.",
    reddit_url: "https://reddit.com/r/webdev",
    reddit_post_id: "jkl012",
    category_id: "8",
    category: mockCategories[7],
    pain_score: 6,
    validation_score: 512,
    upvotes: 15,
    reddit_upvotes: 98,
    reddit_comments: 34,
    market_size: "Medium",
    competition_level: "Low",
    analyzed: true,
    ai_analysis: {
      problem: "Developers waste hours setting up dev environments",
      painLevel: 6,
      targetCustomer: "Web developers, dev teams at startups, bootcamp grads",
      marketSize: "Medium",
      competitionLevel: "Low",
      monetizationIdeas: [
        "Free tier for personal use, $10/mo for teams",
        "Premium templates marketplace (70/30 rev share)",
        "Enterprise support at $500/mo"
      ],
      techStack: ["CLI tool in Rust/Go", "Template repo system", "GitHub API"],
      buildTimeEstimate: "4-6 weeks for CLI + template system",
      keyInsights: [
        "Developer productivity tools are always in demand",
        "Low competition in this specific niche",
        "Could expand to full project scaffolding"
      ]
    },
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    problem: "Online course creators struggle to prevent content piracy",
    description: "My course videos keep getting leaked on Telegram and torrent sites. Lost ~$50K in revenue last year. DRM solutions are too expensive for indie creators.",
    reddit_url: "https://reddit.com/r/entrepreneur",
    reddit_post_id: "mno345",
    category_id: "5",
    category: mockCategories[4],
    pain_score: 9,
    validation_score: 956,
    upvotes: 19,
    reddit_upvotes: 201,
    reddit_comments: 56,
    market_size: "Medium",
    competition_level: "Low",
    analyzed: false,
    ai_analysis: null,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    problem: "Gym owners can't track member engagement effectively",
    description: "50% of new members quit within 3 months. I have no idea why because I can't track their actual gym usage patterns and engagement.",
    reddit_url: "https://reddit.com/r/fitness",
    reddit_post_id: "pqr678",
    category_id: "4",
    category: mockCategories[3],
    pain_score: 7,
    validation_score: 445,
    upvotes: 6,
    reddit_upvotes: 87,
    reddit_comments: 23,
    market_size: "Medium",
    competition_level: "Medium",
    analyzed: false,
    ai_analysis: null,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "7",
    problem: "Shopify store owners overpay for abandoned cart recovery",
    description: "Paying $99/mo just to send automated cart recovery emails seems insane when my profit margins are already thin.",
    reddit_url: "https://reddit.com/r/shopify",
    reddit_post_id: "stu901",
    category_id: "2",
    category: mockCategories[1],
    pain_score: 8,
    validation_score: 734,
    upvotes: 14,
    reddit_upvotes: 143,
    reddit_comments: 41,
    market_size: "Large",
    competition_level: "High",
    analyzed: true,
    ai_analysis: {
      problem: "Shopify store owners overpay for abandoned cart recovery",
      painLevel: 8,
      targetCustomer: "Shopify store owners with $10K-100K monthly revenue",
      marketSize: "Large",
      competitionLevel: "High",
      monetizationIdeas: [
        "Commission-based: 5% of recovered revenue",
        "Flat $29/mo for unlimited emails",
        "Free tier with Shopify branding"
      ],
      techStack: ["Shopify App", "Node.js", "PostgreSQL", "SendGrid"],
      buildTimeEstimate: "8-10 weeks including Shopify app review",
      keyInsights: [
        "Average cart abandonment rate is 70%",
        "Even 10% recovery can mean thousands in revenue",
        "Shopify app store has 8M+ merchants"
      ]
    },
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "8",
    problem: "Podcast editors need better automated transcript editing",
    description: "I spend 2 hours editing transcripts for each 1-hour podcast. AI transcription is 80% there but needs human cleanup. Very tedious.",
    reddit_url: "https://reddit.com/r/podcasting",
    reddit_post_id: "vwx234",
    category_id: "3",
    category: mockCategories[2],
    pain_score: 6,
    validation_score: 389,
    upvotes: 9,
    reddit_upvotes: 76,
    reddit_comments: 19,
    market_size: "Small",
    competition_level: "Low",
    analyzed: false,
    ai_analysis: null,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
